-- Esquema de referencia TaskFlow - Módulo 8 (PostgreSQL).
-- Sequelize crea estas tablas con `npm run db:setup`; este archivo documenta
-- sus claves y relaciones sin incluir datos ni credenciales locales.

CREATE TYPE enum_credentials_role AS ENUM ('user', 'admin');

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(80) NOT NULL,
  email varchar(120) NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE credentials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password_hash varchar(100) NOT NULL,
  role enum_credentials_role NOT NULL DEFAULT 'user',
  user_id integer NOT NULL UNIQUE REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE profiles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bio varchar(240) NOT NULL DEFAULT '',
  avatar_url varchar(255),
  user_id integer NOT NULL UNIQUE REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(80) NOT NULL,
  description varchar(240) NOT NULL DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'pending',
  priority varchar(20) NOT NULL DEFAULT 'medium',
  due_date date,
  user_id integer NOT NULL REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(80) NOT NULL,
  description varchar(240) NOT NULL DEFAULT '',
  owner_id integer NOT NULL REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE project_members (
  user_id integer NOT NULL REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  project_id integer NOT NULL REFERENCES projects(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, project_id)
);

CREATE INDEX tasks_user_id ON tasks(user_id);
CREATE INDEX tasks_status ON tasks(status);
CREATE INDEX tasks_priority ON tasks(priority);
CREATE INDEX projects_owner_id ON projects(owner_id);
